### ISSUE TITLE
Installer needed

### ISSUE THREAD

**Issue by briantrice** [zero-motorcycle-community/zero-log-parser#1]
Plenty of people don't want to upload their logs to a service, and also have trouble getting and running Python, so we should package the script to download, install, and run.

I'm considering https://pypi.python.org/pypi/bbfreeze for this purpose.

**Comment by keithxemi** [comment]
That would help, but would require trusting a downloaded executable. Rewrite the script in js to decode in browser might be a better solution.

**Comment by cecil-t** [comment]
I believe you have already written the in-browser-parser?  Can we close this one out?

**Comment by keithxemi** [comment]
OK, here's a link to the browser version which is offline html, so it meets the need even though not python. https://github.com/zero-motorcycle-community/browser-parse

**Comment by briantrice** [comment]
Thanks, yes!
