### ISSUE TITLE
readme modification suggestion

### ISSUE THREAD

**Issue by glynnelson** [zero-motorcycle-community/zero-log-parser#15]
Hi,

More a comment than an issue, but it took me a while to correctly run the python script simply because I wasn't aware that the command I should be typing was 
python3 zero_log_parser.py XXX.bin

rather than just python.  I suspect this is because my computer has python v 2 and 3 installed, but others may trip up in a similar manner.  The error messages python gives aren't obvious that this was the problem.

Glyn.

**Comment by briantrice** [comment]
Good point! It used to be python 2, but yes it'll be a few years before "python" is unambiguous, and we should be clearer.

I've pushed https://github.com/zero-motorcycle-community/zero-log-parser/commit/f0fd5f32a11457e88ae718cf60762d448bad6138 which fixes this and some other things I noticed while tinkering on this tool.
