### ISSUE TITLE
ValueError: Invalid entry header byte

### ISSUE THREAD

**Issue by briantrice** [zero-motorcycle-community/zero-log-parser#4]
This occurs on a number of test cases found so far. It's not clear that this has one cause or several yet.

**Comment by briantrice** [comment]
Investigation reveals that the current set of places where this occurs is always the first entry, implying that the entries offsets are wrong.

**Comment by keithxemi** [comment]
This is solved. Entry header offset is now corrected as needed to prevent errors.
