### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 0: invalid start byte

### ISSUE THREAD

**Issue by briantrice** [zero-motorcycle-community/zero-log-parser#6]
This has been found on one logfile so far.

**Comment by keithxemi** [comment]
Static addresses are different in this log file. These may have changed for 2017 models. Need more example logs to decide how to handle this.

**Comment by keithxemi** [comment]
Ignore these errors for now. Parse anyway, this produces useful output.
